language: ruby
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
notifications:
  email:
    on_success: change
    on_failure: change
script:
  - bundle exec rubocop
  - bundle exec rspec
cache:
  bundler: true
before_install:
  - gem install bundler
